spring:
  application:
    name: vcit-dev-problem

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true


logging:
  level:
    root: INFO
    com.example: DEBUG
